### ISSUE TITLE
Malware Verification

### ISSUE THREAD

**Issue by ArcherNX01** [svenmauch/WinSlap#15]
This might be a false positive.   Please verify VirusTotal detecting Trojan.Malware.300983.susgen in the WinSlap executable.  I also tried https://virusscan.jotti.org/ but none were found.  However that site checks much fewer apps.  I tired downloaded the MaxSecure app to get rid of the malware but even that app popped up with a malware when I scanned it.   
And if anyone can offer a solution to remove that malware, it would ease my mind.

Thanks!

**Comment by svenmauch** [comment]
If you have downloaded WinSlap from my GitHub, then it is most certainly a false positive. Antivirus software sometimes detects WinSlap as mailicious since it contains a lot of code that changes system settings, registry keys and group policies.

As of today, only one engine (MaxSecure) detects WinSlap as malicious:

- https://virusscan.jotti.org/de-DE/filescanjob/c8y68m71n4
- https://www.virustotal.com/gui/file/e45341a979148485d75d90e5cfe7353d48ff79a8f754db4ad6c794f8bb51144a/detection

Whenever WinSlap is detected by Windows Defender, I open a ticket at Microsoft ask them to remove it from their detection database. This is to make sure that WinSlap works nicely on newly installed machines, where Defender is active by default. I cannot do this for every antivirus software. Feel free to contact your vendor if you would like to see this fixed.
