### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by amithiel** [svenmauch/WinSlap#8]
hi!

A few days ago i fresh installed windows 10 pro 20H2.
I saw a video about this tool on youtube and i had to come here to say thank you!
In the past i used a few scripts that borked my installation, so i was a bit nervous at first, but your tool works like a charm!
I hope you continue to improve it! Many many thanks for helping us have a better experience while dealing with windows!

Cheers

**Comment by svenmauch** [comment]
Hi, thanks for the kind words! I will try and update WinSlap from time to time but won't make any promises.

**Comment by rezorustavi** [comment]
23.04.2021, 17:36, "Sven Mauch" ***@***.***>: Hi, thanks for the kind words! I will try and update WinSlap from time to time but won't make any promises.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.  -- Hi, thanks for the kind words!С уважением, Реваз
